// for admins
#include "./admin/admin.h"
#include "./admin/checker.h"
#include "./admin/loader.h"

// for students
# include "./headers/apple.h"
# include "./headers/ball.h"
# include "./headers/car.h"
# include "./headers/duck.h"
# include "./headers/egg.h"
# include "./headers/fire.h"
# include "./headers/good.h"
# include "./headers/high.h"
# include "./headers/ink.h"
# include "./headers/joy.h"
# include "./headers/kid.h"
# include "./headers/lion.h"
# include "./headers/may.h"
# include "./headers/now.h"
# include "./headers/opt.h"
# include "./headers/pro.h"
# include "./headers/quiz.h"
# include "./headers/rest.h"
# include "./headers/star.h"
# include "./headers/team.h"
# include "./headers/upon.h"
# include "./headers/vest.h"
# include "./headers/work.h"
# include "./headers/xray.h"
# include "./headers/yoyo.h"
# include "./headers/zoo.h"
