const int studentCnt = 0;

# include "apple.h"
# include "ball.h"
# include "car.h"
# include "duck.h"
# include "egg.h"
# include "fire.h"
# include "good.h"
# include "high.h"
# include "ink.h"
# include "joy.h"
# include "kid.h"
# include "lion.h"
# include "may.h"
# include "now.h"
# include "opt.h"
# include "pro.h"
# include "quiz.h"
# include "rest.h"
# include "star.h"
# include "team.h"
# include "upon.h"
# include "vest.h"
# include "work.h"
# include "xray.h"
# include "yoyo.h"
# include "zoo.h"